server:
##服务器端口
  port: 8899
#配置数据库的连接字符串
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exercise?characterEncoding=utf8
    username: root
    password: nahida123
  servlet:
    multipart:
      max-file-size: 10MB
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: springfox-swagger
  devtools:
    restart:
      enabled: true
      exclude: application-dev.yml
  redis:
    port: 6379
    host: '127.0.0.1'

# 设置 Mybatis 的 xml 保存路径
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 配置控制台打印 MyBatis 执行的 SQL
#    map-underscore-to-camel-case: true #将数据库中的下划线命名自动转换成小驼峰命名
mybatis-plus:
  type-aliases-package: com.example.exercise.domain.pojo
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
# 配置打印 MyBatis 执行的 SQL
logging:
  level:
    com:
      design:
        competition: debug




